name: Build

on:
  push:
    branches:
      - master

jobs:
  setup:
    name: Setup environment
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: echo Setup...

  build:
    name: ${{ matrix.wheel }} (${{matrix.test}})
    runs-on: ubuntu-latest
    needs: setup
    container:
      image: debian:10

    strategy:
      matrix:
        wheel:
          - demo
          - demo2
        test:
          - 1
          - 2
          - 3
          - 4
          - 5

    steps:
      - uses: actions/checkout@v2

      - name: Execute ${{ matrix.wheel }}/build.sh
        run: |
          exec ${{ matrix.wheel }}/build.sh

  done:
    name: Done with environment
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo Done...
