name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.wheel }} (${{matrix.test}})
    runs-on: ubuntu-latest
    container:
      image: debian:10

    strategy:
      matrix:
        wheel:
          - demo
        #   - demo2
        test:
          - 1
        #   - 2
        #   - 3
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute ${{ matrix.wheel }}/build.sh
        run: exec ${{ matrix.wheel }}/build.sh

      - name: Upload ${{ matrix.wheel }}-${{ matrix.test }}.txt
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');

            const path = 'artifact.txt';
            const name = '${{ matrix.wheel }}-${{ matrix.test }}'artifact.txt';

            const assets = await github.repos.listAssetsForRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: 24946958,
            });
            console.log(assets);
            const [asset] = (assets.data || assets).filter(a => a.name === name);
            if(asset) {
              await github.repos.deleteReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                asset_id: asset.id,
              });
            }

            await github.repos.uploadReleaseAsset({
              url: 'https://uploads.github.com/repos/mgjm/github-action-test/releases/24946958/assets{?name,label}',
              headers: {
                'content-type': 'text/plain',
                'content-length': fs.statSync(path).size,
              },
              name,
              file: fs.readFileSync(path),
            });
