name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.wheel }}
    runs-on: ubuntu-latest
    container:
      image: debian:10

    strategy:
      matrix:
        wheel:
          - demo

    steps:
      - uses: actions/checkout@v2

      - name: Execute ${{ matrix.wheel }}/build.sh
        run: |
          exec ${{ matrix.wheel }}/build.sh
