name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.wheel }} (${{matrix.test}})
    runs-on: ubuntu-latest
    container:
      image: debian:10

    strategy:
      matrix:
        wheel:
          - demo
        #   - demo2
        test:
          - 1
        #   - 2
        #   - 3
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute ${{ matrix.wheel }}/build.sh
        run: exec ${{ matrix.wheel }}/build.sh

      - name: Upload ${{ matrix.wheel }}-${{ matrix.test }}.txt
        uses: actions/upload-release-asset@v1
        with:
          upload_url: https://uploads.github.com/repos/mgjm/github-action-test/releases/1/assets{?name,label}
          asset_path: artifact.txt
          asset_name: ${{ matrix.wheel }}-${{ matrix.test }}.txt
          asset_content_type: text/plain
