name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.wheel }} (${{matrix.test}})
    runs-on: ubuntu-latest
    container:
      image: debian:10

    strategy:
      matrix:
        wheel:
          - demo
        #   - demo2
        test:
          - 1
        #   - 2
        #   - 3
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute ${{ matrix.wheel }}/build.sh
        run: exec ${{ matrix.wheel }}/build.sh

      - name: Upload ${{ matrix.wheel }}-${{ matrix.test }}.txt
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const path = 'artifact.txt';
            await github.repos.uploadReleaseAsset({
              url: 'https://uploads.github.com/repos/mgjm/github-action-test/releases/24946958/assets{?name,label}',
              headers: {
                'content-type': 'text/plain',
                'content-length': fs.statSync(path).size,
              },
              name: '${{ matrix.wheel }}-${{ matrix.test }}.txt',
              file: fs.readFileSync(path),
            });
