name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.wheel }} (${{matrix.test}})
    runs-on: ubuntu-latest
    container:
      image: debian:10

    strategy:
      matrix:
        wheel:
          - demo
        #   - demo2
        test:
          - 1
        #   - 2
        #   - 3
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute ${{ matrix.wheel }}/build.sh
        run: exec ${{ matrix.wheel }}/build.sh

      - name: Upload ${{ matrix.wheel }}-${{ matrix.test }}.txt
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');

            const release = 24946958;
            const path = 'artifact.txt';
            const name = '${{ matrix.wheel }}-${{ matrix.test }}.txt';

            console.log('Fetch current assets');
            const assets = await github.repos.listAssetsForRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release,
            });
            const [asset] = assets.data.filter(a => a.name === name);
            if(asset) {
              console.log(`Delete asset ${asset.id}`);
              await github.repos.deleteReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                asset_id: asset.id,
              });
            }

            console.log(`Upload asset ${name}`);
            await github.repos.uploadReleaseAsset({
              url: `https://uploads.github.com/repos/${context.repo.owner}/${context.repo.repo}/releases/${release}/assets{?name,label}`,
              headers: {
                'content-type': 'text/plain',
                'content-length': fs.statSync(path).size,
              },
              name,
              data: fs.readFileSync(path),
            });
