name: ci

on:
  - push

jobs:
  build:
    name: ${{ matrix.command }}
    runs-on: ubuntu-latest
    container:
      image: mgjm/rust-ci
      env:
        RUSTFLAGS: -D warnings

    strategy:
      matrix:
        command:
          - cargo test
          - cargo clippy
          # - cargo fmt -- --check
          # - rm LICENSE-* && cargo apply-license && git add . && git diff --cached --exit-code
          # - cargo readme | diff README.md /dev/stdin
          # - find . -name Cargo.toml -exec cargo sort-ck {} +
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup test as clippy
        if: ${{ matrix.command == 'cargo test' }}
        run: echo -e '#!/bin/sh -e\n\nexec cargo test --no-fail-fast "$@"' > "`which cargo-clippy`"

      - name: Run clippy
        if: ${{ matrix.command == 'cargo test' }}
        run: cargo clippy --message-format=json || true

      - name: ${{ matrix.command }}
        if: ${{ matrix.command != 'cargo clippy' && matrix.command != 'cargo test' }}
        run: ${{ matrix.command }}

      - name: ${{ matrix.command }}
        if: ${{ matrix.command == 'cargo clippy' || matrix.command == 'cargo test' }}
        uses: actions-rs/clippy-check@v1
        with:
          name: ${{ matrix.command }}
          token: ${{ secrets.GITHUB_TOKEN }}
