name: CI

on:
  - push

jobs:
  build:
    name: ${{ matrix.wheel }} (${{matrix.test}})
    runs-on: ubuntu-latest
    container:
      image: mgjm/rust-ci
      env:
        RUSTFLAGS: -D warnings

    strategy:
      matrix:
        command:
          - cargo test
          - cargo clippy
          - cargo fmt -- --check
          - rm LICENSE-* && cargo apply-license && git diff --exit-code LICENSE-*
          - cargo readme | diff README.md /dev/stdin
          - find . -name Cargo.toml -exec cargo sort-ck {} +
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ${{ matrix.command }}
        run: ${{ matrix.command }}
